#!/bin/bash
#
# Nagios check that uses killall -0 to reliably determine if
# a given process is running. This is written to replace
# check_procs, which does not work well because of column
# limits of ps
#
set -e
if [ -z "$1" ]
then
  echo "Must pass process name"
  exit 3
fi

killall -0 $1

ret_code=$?
if [[ $ret_code = 1 ]]; then
  echo "Process ${1} is not running"
  exit 2
else
  echo "Process ${1} is running!"
  exit $ret_code
fi
